DROP TABLE IF EXISTS EPGList;

CREATE TABLE IF NOT EXISTS EPGList(
	id INT(11) NOT NULL AUTO_INCREMENT,
	ONID INT(11),
	TSID INT(11),
	SID INT(11),
	EID INT(11),
	
	startTime DOUBLE,
	duration DOUBLE,
	eventName VARCHAR(255),
	eventName_language VARCHAR(255),
	eventText_language VARCHAR(255),
	PRIMARY KEY(id)


)ENGINE=INNODB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS Transport;
CREATE TABLE IF NOT EXISTS Transport(
	id VARCHAR(255) PRIMARY KEY NOT NULL,
	frequency VARCHAR(255),
	PMTPID INT(11),
	PCRPID INT(11)

)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS ESList;
CREATE TABLE IF NOT EXISTS ESList(
	id VARCHAR(255) PRIMARY KEY NOT NULL,
	streamType VARCHAR(255),
	PID INT(11),
	scrambled VARCHAR(255),
	languageCode VARCHAR(255)

)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS Transport_ESList;
CREATE TABLE IF NOT EXISTS Transport_ESList(
	transport_id VARCHAR(255) NOT NULL,
	es_id VARCHAR(255) NOT NULL,
	PRIMARY KEY(transport_id,es_id),
	FOREIGN KEY (transport_id) REFERENCES Transport(id),
	FOREIGN KEY (es_id) REFERENCES ESList(id)

)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS ProgramList;
CREATE TABLE IF NOT EXISTS ProgramList(
	id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ONID INT(11),
	TSID INT(11),
	SID INT(11),
	logicalNumber INT(11),
	
	`name` VARCHAR(255),
	multilingualName VARCHAR(255),
	multilingualName_language VARCHAR(255),
	provider VARCHAR(255),
	serviceType VARCHAR(255),
	scrambled VARCHAR(255),
	transport_id VARCHAR(255) NOT NULL,
	FOREIGN KEY(transport_id) REFERENCES Transport(id)
	
)ENGINE=INNODB DEFAULT CHARSET=utf8;